"""add model constraints

Revision ID: f96764623b86
Revises: bc5d55914f76
Create Date: 2026-07-18 13:34:16.497886

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

project_role_enum = sa.Enum(
    "owner",
    "participant",
    name="projectrole",
    schema="epam",
)


# revision identifiers, used by Alembic.
revision: str = 'f96764623b86'
down_revision: Union[str, Sequence[str], None] = 'bc5d55914f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('documents_project_id_fkey'), 
        'documents', 
        schema='epam', 
        type_='foreignkey'
    )
    op.drop_constraint(
        op.f('documents_uploaded_by_fkey'), 
        'documents', 
        schema='epam', 
        type_='foreignkey'
    )
    op.create_foreign_key(
        "documents_uploaded_by_fkey", 
        'documents', 
        'users', 
        ['uploaded_by'], 
        ['id'], 
        source_schema='epam', 
        referent_schema='epam', 
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        "documents_project_id_fkey", 
        'documents', 
        'projects', 
        ['project_id'], 
        ['id'], 
        source_schema='epam', 
        referent_schema='epam', 
        ondelete='CASCADE'
    )
    project_role_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column(
        "project_members",
        "role",
        existing_type=sa.VARCHAR(length=20),
        type_=project_role_enum,
        existing_nullable=False,
        schema="epam",
        postgresql_using="role::text::epam.projectrole",
    )
    op.drop_constraint(
        op.f('project_members_project_id_fkey'), 
        'project_members', 
        schema='epam', 
        type_='foreignkey'
    )
    op.drop_constraint(
        op.f('project_members_user_id_fkey'), 
        'project_members', 
        schema='epam', 
        type_='foreignkey'
    )
    op.create_foreign_key(
        "project_members_user_id_fkey", 
        'project_members', 
        'users', 
        ['user_id'], 
        ['id'], 
        source_schema='epam', 
        referent_schema='epam', 
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        "project_members_project_id_fkey", 
        'project_members', 
        'projects', 
        ['project_id'], 
        ['id'], 
        source_schema='epam', 
        referent_schema='epam', 
        ondelete='CASCADE'
    )
    op.drop_constraint(
        op.f('projects_owner_id_fkey'), 
        'projects', 
        schema='epam', 
        type_='foreignkey'
    )
    op.create_foreign_key(
        "projects_owner_id_fkey", 
        'projects', 
        'users', 
        ['owner_id'], 
        ['id'], 
        source_schema='epam', 
        referent_schema='epam', 
        ondelete='CASCADE'
    )
    op.create_check_constraint(
        "chk_documents_size",
        "documents",
        "size >= 0",
        schema="epam",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "projects_owner_id_fkey", 
        'projects', 
        schema='epam', 
        type_='foreignkey'
    )
    op.create_foreign_key(
        op.f('projects_owner_id_fkey'), 
        'projects', 
        'users', 
        ['owner_id'], 
        ['id'], 
        source_schema='epam', 
        referent_schema='epam'
    )
    op.drop_constraint(
        "project_members_user_id_fkey", 
        'project_members', 
        schema='epam', 
        type_='foreignkey'
    )
    op.drop_constraint(
        "project_members_project_id_fkey", 
        'project_members', 
        schema='epam', 
        type_='foreignkey'
    )
    op.create_foreign_key(
        op.f('project_members_user_id_fkey'), 
        'project_members', 
        'users', 
        ['user_id'], 
        ['id'], 
        source_schema='epam', 
        referent_schema='epam'
    )
    op.create_foreign_key(
        op.f('project_members_project_id_fkey'), 
        'project_members', 
        'projects', 
        ['project_id'], 
        ['id'], 
        source_schema='epam', 
        referent_schema='epam'
    )
    op.alter_column('project_members', 'role',
               existing_type=sa.Enum(
                    "owner",
                    "participant",
                    name="projectrole",
                    schema="epam",
                ),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               schema='epam')
    op.drop_constraint(
        "documents_uploaded_by_fkey", 
        'documents', 
        schema='epam', 
        type_='foreignkey'
    )
    op.drop_constraint(
        "documents_project_id_fkey", 
        'documents', 
        schema='epam', 
        type_='foreignkey'
    )
    op.create_foreign_key(
        op.f('documents_uploaded_by_fkey'), 
        'documents', 
        'users', 
        ['uploaded_by'], 
        ['id'], 
        source_schema='epam', 
        referent_schema='epam'
        )
    op.create_foreign_key(
        op.f('documents_project_id_fkey'), 
        'documents', 
        'projects', 
        ['project_id'], 
        ['id'], 
        source_schema='epam', 
        referent_schema='epam'
        )
    op.drop_constraint(
        "chk_documents_size",
        "documents",
        schema="epam",
        type_="check",
    )
    project_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
